* General instructions

  Current structure is:
  - ./examples
    - ./examples/torch
    - ./examples/torch/<specific-example>

  - Every <specific-example> should have a description file.
    - Should be either on a markup language or simple text.
  - Every <specific-example> should have a requirement.txt
    - This should have only the imported libraries, anything else

* Interface design   
  
  Generally, the deepworlds setup tool is going to be like a 
  command line tools. Users will use it as an out-of-box tool
  in order to create new worlds or use the existing ones.
 
  Consequently, every <specific-example> might have different 
  worlds or even different solution (supervisor, agent, robots).
  It is essential that the deepworlds setup tools knows
  about those different aspects of every problem. As result, every 
  <specific-example> should have a formated string that can be 
  interpreted by the setup tools. General, information should be 
  included in this string.
  
  + Name 
  + Path
  + Short description
  + Long Description
  + Requirements (or the path only)
  + Authors 
    + Name
    + Email
    + (optional) Github Account 
  + Webots version
  + Deebots version
  + Worlds 
  + Supervisors-Robots (array or dice)
  + (optional) Framework which is used
    + Version of the framework 
  + (optional) Future Work 
  + (optional) Related papers 
  + (optional) Other
      
  This information should be easily accessible by the developers
  and also by the user. Developer should have the option to add
  those information when they are about to start a project. On 
  the other hand, user should have the option to "scroll" on 
  those information in order to choose which 
  
